#!/usr/bin/env perl

use strict;
use warnings;

use File::Basename 'dirname';
use File::Spec;

use lib join '/', File::Spec->splitdir(dirname(__FILE__)), 'lib';
use lib join '/', File::Spec->splitdir(dirname(__FILE__)), '..', 'lib';
use local::lib join '/', File::Spec->splitdir(dirname(__FILE__)), '..', 'extlib';

# Check if Mojo is installed
eval 'use Mojolicious::Commands';
die <<EOF if $@;
It looks like you don't have the Mojolicious Framework installed.
Please visit http://mojolicious.org for detailed installation instructions.

EOF

# Application
$ENV{MOJO_APP} ||= 'Mvac::Sample';

use Plack::Builder;
builder {
    enable "Plack::Middleware::Static",
        path => qr{^/(images|js|css|photos)/}, root => "statics/";
    Mojolicious::Commands->start;
};
